### ISSUE TITLE
Long prompt  error despite higher maxretries, shot prompt : no problem

### ISSUE THREAD

**Issue by RomainLLC** [eDiasoft/midjourney-api-php#6]
Hello,

first thanks for your work and this useful PHP lib!

I'm building a [web app](https://twitter.com/Romain_LLC/status/1701735147995791627) using your cool lib, 
but there is someting i can't explain :  long prompts fail as image is never retrieved, though shorter ones succeed.

Example : 

- short prompt always  success example :

`a border-collie playing with bubbles in a garden full of trees`

- longer prompt always fails example: 

`full body photo of a spanish woman wearing black lingerie waking up looking through a window at the city of Paris, detailed, full body lots of feminity, alluring, dazzling, mischievous smile, sensual pose, muse, intricately detailed, beautifully color - coded, unreal engine, octane render, natural lighting`

Message is sent to Discord, image is generated, but never retrieved with the long one.

The error is the following, though i increased MaxRetries to 30 and interval to 15s :

`eDiasoft\Midjourney\Exceptions\MidjourneyException: Max tries exceeded, increase the max try attempt ($midjourney->imagine(*)->setMaxRetries(30)) or check your discord what went wrong. in eDiasoft\Midjourney\Commands\Imagine->retrieveGeneratedImage()`

If you have an idea or a clue, i'm your man to help solve this issue.

**Comment by ShuCh3n** [comment]
Dear @RomainLLC 

Excellent you like the project and I'm happy I can contribute to your project. The issue you mention is not so much that the prompt is too long but the content is too explicit. Midjourney will hide images that tend to be NSFW, so the library won't be able to retrieve the response because it's not shown to the public.

![github_issue_6](https://github.com/eDiasoft/midjourney-api-php/assets/7081446/0222b2b0-f799-4140-82a0-7cc96611b6a5)

**Comment by RomainLLC** [comment]
Hello,

you're right, i'm sorry i did not see this -i was sure  NSFW filter would prevent image generation, but i saw the image and it was deleted afterwards.

Be sure i'll double check before opening a non-issue :)))
